-- -------------------------------------------------------------
-- 
-- File Name: hdlsrc/fft_16_bit/fft_16_bit.vhd
-- Created: 2017-03-27 23:13:58
-- 
-- Generated by MATLAB 9.1 and HDL Coder 3.9
-- 
-- 
-- -------------------------------------------------------------
-- Rate and Clocking Details
-- -------------------------------------------------------------
-- Model base rate: 0.2
-- Target subsystem base rate: 0.2
-- 
-- 
-- Clock Enable  Sample Time
-- -------------------------------------------------------------
-- ce_out        0.2
-- -------------------------------------------------------------
-- 
-- 
-- Output Signal                 Clock Enable  Sample Time
-- -------------------------------------------------------------
-- Out1_re                       ce_out        0.2
-- Out1_im                       ce_out        0.2
-- Out2                          ce_out        0.2
-- -------------------------------------------------------------
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: fft_16_bit
-- Source Path: fft_16_bit
-- Hierarchy Level: 0
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.fft_16_bit_pkg.ALL;

ENTITY fft_16_bit IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        clk_enable                        :   IN    std_logic;
        In1                               :   IN    vector_of_std_logic_vector16(0 TO 15);  -- uint16 [16]
        ce_out                            :   OUT   std_logic;
        Out1_re                           :   OUT   vector_of_std_logic_vector21(0 TO 15);  -- sfix21 [16]
        Out1_im                           :   OUT   vector_of_std_logic_vector21(0 TO 15);  -- sfix21 [16]
        Out2                              :   OUT   std_logic
        );
END fft_16_bit;


ARCHITECTURE rtl OF fft_16_bit IS

  -- Component Declarations
  COMPONENT FFT_HDL_Optimized
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          dataIn                          :   IN    vector_of_std_logic_vector16(0 TO 15);  -- uint16 [16]
          validIn                         :   IN    std_logic;
          dataOut_re                      :   OUT   vector_of_std_logic_vector21(0 TO 15);  -- sfix21 [16]
          dataOut_im                      :   OUT   vector_of_std_logic_vector21(0 TO 15);  -- sfix21 [16]
          validOut                        :   OUT   std_logic
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : FFT_HDL_Optimized
    USE ENTITY work.FFT_HDL_Optimized(rtl);

  -- Signals
  SIGNAL Constant_out1                    : std_logic;
  SIGNAL FFT_HDL_Optimized_out1_re        : vector_of_std_logic_vector21(0 TO 15);  -- ufix21 [16]
  SIGNAL FFT_HDL_Optimized_out1_im        : vector_of_std_logic_vector21(0 TO 15);  -- ufix21 [16]
  SIGNAL FFT_HDL_Optimized_out2           : std_logic;

BEGIN
  u_FFT_HDL_Optimized : FFT_HDL_Optimized
    PORT MAP( clk => clk,
              reset => reset,
              enb => clk_enable,
              dataIn => In1,  -- uint16 [16]
              validIn => Constant_out1,
              dataOut_re => FFT_HDL_Optimized_out1_re,  -- sfix21 [16]
              dataOut_im => FFT_HDL_Optimized_out1_im,  -- sfix21 [16]
              validOut => FFT_HDL_Optimized_out2
              );

  Constant_out1 <= '1';

  ce_out <= clk_enable;

  Out1_re <= FFT_HDL_Optimized_out1_re;

  Out1_im <= FFT_HDL_Optimized_out1_im;

  Out2 <= FFT_HDL_Optimized_out2;

END rtl;

