-- -------------------------------------------------------------
-- 
-- File Name: hdlsrc/fft_16_bit/fft_16_bit_pkg.vhd
-- Created: 2017-03-27 23:13:58
-- 
-- Generated by MATLAB 9.1 and HDL Coder 3.9
-- 
-- -------------------------------------------------------------


LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

PACKAGE fft_16_bit_pkg IS
  TYPE vector_of_signed17 IS ARRAY (NATURAL RANGE <>) OF signed(16 DOWNTO 0);
  TYPE vector_of_std_logic_vector16 IS ARRAY (NATURAL RANGE <>) OF std_logic_vector(15 DOWNTO 0);
  TYPE vector_of_std_logic_vector21 IS ARRAY (NATURAL RANGE <>) OF std_logic_vector(20 DOWNTO 0);
END fft_16_bit_pkg;

