-- -------------------------------------------------------------
-- 
-- File Name: hdlsrc/fft_16_bit/RADIX22FFT_SDNF2_2_block1.vhd
-- Created: 2017-03-27 23:13:58
-- 
-- Generated by MATLAB 9.1 and HDL Coder 3.9
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: RADIX22FFT_SDNF2_2_block1
-- Source Path: fft_16_bit/FFT HDL Optimized/RADIX22FFT_SDNF2_2
-- Hierarchy Level: 2
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY RADIX22FFT_SDNF2_2_block1 IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        rotate_5                          :   IN    std_logic;  -- ufix1
        dout_5_re                         :   IN    std_logic_vector(17 DOWNTO 0);  -- sfix18
        dout_5_im                         :   IN    std_logic_vector(17 DOWNTO 0);  -- sfix18
        dout_13_re                        :   IN    std_logic_vector(17 DOWNTO 0);  -- sfix18
        dout_13_im                        :   IN    std_logic_vector(17 DOWNTO 0);  -- sfix18
        dout_1_vld                        :   IN    std_logic;
        softReset                         :   IN    std_logic;
        dout_5_re_1                       :   OUT   std_logic_vector(18 DOWNTO 0);  -- sfix19
        dout_5_im_1                       :   OUT   std_logic_vector(18 DOWNTO 0);  -- sfix19
        dout_6_re                         :   OUT   std_logic_vector(18 DOWNTO 0);  -- sfix19
        dout_6_im                         :   OUT   std_logic_vector(18 DOWNTO 0);  -- sfix19
        dout_2_vld                        :   OUT   std_logic
        );
END RADIX22FFT_SDNF2_2_block1;


ARCHITECTURE rtl OF RADIX22FFT_SDNF2_2_block1 IS

  -- Signals
  SIGNAL dout_5_re_signed                 : signed(17 DOWNTO 0);  -- sfix18
  SIGNAL din1_re                          : signed(18 DOWNTO 0);  -- sfix19
  SIGNAL dout_5_im_signed                 : signed(17 DOWNTO 0);  -- sfix18
  SIGNAL din1_im                          : signed(18 DOWNTO 0);  -- sfix19
  SIGNAL dout_13_re_signed                : signed(17 DOWNTO 0);  -- sfix18
  SIGNAL din2_re                          : signed(18 DOWNTO 0);  -- sfix19
  SIGNAL dout_13_im_signed                : signed(17 DOWNTO 0);  -- sfix18
  SIGNAL din2_im                          : signed(18 DOWNTO 0);  -- sfix19
  SIGNAL Radix22ButterflyG2_NF_din_vld_dly : std_logic;
  SIGNAL Radix22ButterflyG2_NF_btf1_re_reg : signed(19 DOWNTO 0);  -- sfix20
  SIGNAL Radix22ButterflyG2_NF_btf1_im_reg : signed(19 DOWNTO 0);  -- sfix20
  SIGNAL Radix22ButterflyG2_NF_btf2_re_reg : signed(19 DOWNTO 0);  -- sfix20
  SIGNAL Radix22ButterflyG2_NF_btf2_im_reg : signed(19 DOWNTO 0);  -- sfix20
  SIGNAL Radix22ButterflyG2_NF_din_vld_dly_next : std_logic;
  SIGNAL Radix22ButterflyG2_NF_btf1_re_reg_next : signed(19 DOWNTO 0);  -- sfix20
  SIGNAL Radix22ButterflyG2_NF_btf1_im_reg_next : signed(19 DOWNTO 0);  -- sfix20
  SIGNAL Radix22ButterflyG2_NF_btf2_re_reg_next : signed(19 DOWNTO 0);  -- sfix20
  SIGNAL Radix22ButterflyG2_NF_btf2_im_reg_next : signed(19 DOWNTO 0);  -- sfix20
  SIGNAL dout_5_re_tmp                    : signed(18 DOWNTO 0);  -- sfix19
  SIGNAL dout_5_im_tmp                    : signed(18 DOWNTO 0);  -- sfix19
  SIGNAL dout_6_re_tmp                    : signed(18 DOWNTO 0);  -- sfix19
  SIGNAL dout_6_im_tmp                    : signed(18 DOWNTO 0);  -- sfix19

BEGIN
  dout_5_re_signed <= signed(dout_5_re);

  din1_re <= resize(dout_5_re_signed, 19);

  dout_5_im_signed <= signed(dout_5_im);

  din1_im <= resize(dout_5_im_signed, 19);

  dout_13_re_signed <= signed(dout_13_re);

  din2_re <= resize(dout_13_re_signed, 19);

  dout_13_im_signed <= signed(dout_13_im);

  din2_im <= resize(dout_13_im_signed, 19);

  -- Radix22ButterflyG2_NF
  Radix22ButterflyG2_NF_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Radix22ButterflyG2_NF_din_vld_dly <= '0';
      Radix22ButterflyG2_NF_btf1_re_reg <= to_signed(16#00000#, 20);
      Radix22ButterflyG2_NF_btf1_im_reg <= to_signed(16#00000#, 20);
      Radix22ButterflyG2_NF_btf2_re_reg <= to_signed(16#00000#, 20);
      Radix22ButterflyG2_NF_btf2_im_reg <= to_signed(16#00000#, 20);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Radix22ButterflyG2_NF_din_vld_dly <= Radix22ButterflyG2_NF_din_vld_dly_next;
        Radix22ButterflyG2_NF_btf1_re_reg <= Radix22ButterflyG2_NF_btf1_re_reg_next;
        Radix22ButterflyG2_NF_btf1_im_reg <= Radix22ButterflyG2_NF_btf1_im_reg_next;
        Radix22ButterflyG2_NF_btf2_re_reg <= Radix22ButterflyG2_NF_btf2_re_reg_next;
        Radix22ButterflyG2_NF_btf2_im_reg <= Radix22ButterflyG2_NF_btf2_im_reg_next;
      END IF;
    END IF;
  END PROCESS Radix22ButterflyG2_NF_process;

  Radix22ButterflyG2_NF_output : PROCESS (Radix22ButterflyG2_NF_din_vld_dly, Radix22ButterflyG2_NF_btf1_re_reg,
       Radix22ButterflyG2_NF_btf1_im_reg, Radix22ButterflyG2_NF_btf2_re_reg,
       Radix22ButterflyG2_NF_btf2_im_reg, din1_re, din1_im, din2_re, din2_im,
       dout_1_vld, rotate_5)
  BEGIN
    Radix22ButterflyG2_NF_btf1_re_reg_next <= Radix22ButterflyG2_NF_btf1_re_reg;
    Radix22ButterflyG2_NF_btf1_im_reg_next <= Radix22ButterflyG2_NF_btf1_im_reg;
    Radix22ButterflyG2_NF_btf2_re_reg_next <= Radix22ButterflyG2_NF_btf2_re_reg;
    Radix22ButterflyG2_NF_btf2_im_reg_next <= Radix22ButterflyG2_NF_btf2_im_reg;
    Radix22ButterflyG2_NF_din_vld_dly_next <= dout_1_vld;
    IF rotate_5 /= '0' THEN 
      IF dout_1_vld = '1' THEN 
        Radix22ButterflyG2_NF_btf1_re_reg_next <= resize(din1_re, 20) + resize(din2_im, 20);
        Radix22ButterflyG2_NF_btf2_re_reg_next <= resize(din1_re, 20) - resize(din2_im, 20);
        Radix22ButterflyG2_NF_btf2_im_reg_next <= resize(din1_im, 20) + resize(din2_re, 20);
        Radix22ButterflyG2_NF_btf1_im_reg_next <= resize(din1_im, 20) - resize(din2_re, 20);
      END IF;
    ELSIF dout_1_vld = '1' THEN 
      Radix22ButterflyG2_NF_btf1_re_reg_next <= resize(din1_re, 20) + resize(din2_re, 20);
      Radix22ButterflyG2_NF_btf2_re_reg_next <= resize(din1_re, 20) - resize(din2_re, 20);
      Radix22ButterflyG2_NF_btf1_im_reg_next <= resize(din1_im, 20) + resize(din2_im, 20);
      Radix22ButterflyG2_NF_btf2_im_reg_next <= resize(din1_im, 20) - resize(din2_im, 20);
    END IF;
    dout_5_re_tmp <= Radix22ButterflyG2_NF_btf1_re_reg(18 DOWNTO 0);
    dout_5_im_tmp <= Radix22ButterflyG2_NF_btf1_im_reg(18 DOWNTO 0);
    dout_6_re_tmp <= Radix22ButterflyG2_NF_btf2_re_reg(18 DOWNTO 0);
    dout_6_im_tmp <= Radix22ButterflyG2_NF_btf2_im_reg(18 DOWNTO 0);
    dout_2_vld <= Radix22ButterflyG2_NF_din_vld_dly;
  END PROCESS Radix22ButterflyG2_NF_output;


  dout_6_re <= std_logic_vector(dout_6_re_tmp);

  dout_6_im <= std_logic_vector(dout_6_im_tmp);

  dout_5_re_1 <= std_logic_vector(dout_5_re_tmp);

  dout_5_im_1 <= std_logic_vector(dout_5_im_tmp);

END rtl;

