-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj/hdlsrc/hdl_ofdm_tx/hdl_modulator/hdl_modulator_sincos_hdl.vhd
-- Created: 2018-02-27 13:25:15
-- 
-- Generated by MATLAB 9.3 and HDL Coder 3.11
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: hdl_modulator_sincos_hdl
-- Source Path: hdl_modulator/wave_generator/sincos hdl
-- Hierarchy Level: 3
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY hdl_modulator_sincos_hdl IS
  PORT( In1                               :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En14
        Out1                              :   OUT   std_logic_vector(15 DOWNTO 0);  -- sfix16_En14
        Out2                              :   OUT   std_logic_vector(15 DOWNTO 0)  -- sfix16_En14
        );
END hdl_modulator_sincos_hdl;


ARCHITECTURE rtl OF hdl_modulator_sincos_hdl IS

  -- Component Declarations
  COMPONENT hdl_modulator_sin_hdl
    PORT( In1                             :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En14
          y                               :   OUT   std_logic_vector(15 DOWNTO 0)  -- sfix16_En14
          );
  END COMPONENT;

  COMPONENT hdl_modulator_cos_hdl
    PORT( In1                             :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En14
          x                               :   OUT   std_logic_vector(15 DOWNTO 0)  -- sfix16_En14
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : hdl_modulator_sin_hdl
    USE ENTITY work.hdl_modulator_sin_hdl(rtl);

  FOR ALL : hdl_modulator_cos_hdl
    USE ENTITY work.hdl_modulator_cos_hdl(rtl);

  -- Signals
  SIGNAL Sine                             : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL Cosine                           : std_logic_vector(15 DOWNTO 0);  -- ufix16

BEGIN
  u_sin_hdl : hdl_modulator_sin_hdl
    PORT MAP( In1 => In1,  -- sfix16_En14
              y => Sine  -- sfix16_En14
              );

  u_cos_hdl : hdl_modulator_cos_hdl
    PORT MAP( In1 => In1,  -- sfix16_En14
              x => Cosine  -- sfix16_En14
              );

  Out1 <= Sine;

  Out2 <= Cosine;

END rtl;

