-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj/hdlsrc/hdl_ofdm_tx/hdl_modulator/hdl_modulator_wave_generator.vhd
-- Created: 2018-02-27 13:25:15
-- 
-- Generated by MATLAB 9.3 and HDL Coder 3.11
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: hdl_modulator_wave_generator
-- Source Path: hdl_modulator/wave_generator
-- Hierarchy Level: 2
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY hdl_modulator_wave_generator IS
  PORT( u                                 :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En14
        x                                 :   OUT   std_logic_vector(15 DOWNTO 0);  -- sfix16_En14
        y                                 :   OUT   std_logic_vector(15 DOWNTO 0)  -- sfix16_En14
        );
END hdl_modulator_wave_generator;


ARCHITECTURE rtl OF hdl_modulator_wave_generator IS

  -- Component Declarations
  COMPONENT hdl_modulator_sincos_hdl
    PORT( In1                             :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En14
          Out1                            :   OUT   std_logic_vector(15 DOWNTO 0);  -- sfix16_En14
          Out2                            :   OUT   std_logic_vector(15 DOWNTO 0)  -- sfix16_En14
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : hdl_modulator_sincos_hdl
    USE ENTITY work.hdl_modulator_sincos_hdl(rtl);

  -- Signals
  SIGNAL Sine                             : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL Cosine                           : std_logic_vector(15 DOWNTO 0);  -- ufix16

BEGIN
  u_sincos_hdl : hdl_modulator_sincos_hdl
    PORT MAP( In1 => u,  -- sfix16_En14
              Out1 => Sine,  -- sfix16_En14
              Out2 => Cosine  -- sfix16_En14
              );

  x <= Sine;

  y <= Cosine;

END rtl;

