-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj/hdlsrc/hdl_ofdm_tx/hdl_ofdm_tx_tc.vhd
-- Created: 2018-02-27 13:25:18
-- 
-- Generated by MATLAB 9.3 and HDL Coder 3.11
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: hdl_ofdm_tx_tc
-- Source Path: hdl_ofdm_tx_tc
-- Hierarchy Level: 1
-- 
-- Master clock enable input: clk_enable
-- 
-- enb         : identical to clk_enable
-- enb_1_1_1   : identical to clk_enable
-- enb_1_16_0  : 16x slower than clk with last phase
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY hdl_ofdm_tx_tc IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        clk_enable                        :   IN    std_logic;
        enb                               :   OUT   std_logic;
        enb_1_1_1                         :   OUT   std_logic;
        enb_1_16_0                        :   OUT   std_logic
        );
END hdl_ofdm_tx_tc;


ARCHITECTURE rtl OF hdl_ofdm_tx_tc IS

  -- Signals
  SIGNAL count16                          : unsigned(3 DOWNTO 0);  -- ufix4
  SIGNAL phase_all                        : std_logic;
  SIGNAL phase_0                          : std_logic;
  SIGNAL phase_0_tmp                      : std_logic;

BEGIN
  Counter16 : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      count16 <= to_unsigned(1, 4);
    ELSIF clk'event AND clk = '1' THEN
      IF clk_enable = '1' THEN
        IF count16 >= to_unsigned(15, 4) THEN
          count16 <= to_unsigned(0, 4);
        ELSE
          count16 <= count16 + to_unsigned(1, 4);
        END IF;
      END IF;
    END IF; 
  END PROCESS Counter16;

  phase_all <= '1' WHEN clk_enable = '1' ELSE '0';

  temp_process1 : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      phase_0 <= '0';
    ELSIF clk'event AND clk = '1' THEN
      IF clk_enable = '1' THEN
        phase_0 <= phase_0_tmp;
      END IF;
    END IF; 
  END PROCESS temp_process1;

  phase_0_tmp <= '1' WHEN count16 = to_unsigned(15, 4) AND clk_enable = '1' ELSE '0';

  enb <=  phase_all AND clk_enable;

  enb_1_1_1 <=  phase_all AND clk_enable;

  enb_1_16_0 <=  phase_0 AND clk_enable;


END rtl;

