-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj/hdlsrc/hdl_modulator/hdl_modulator_pac.vhd
-- Created: 2018-02-20 12:01:50
-- 
-- Generated by MATLAB 9.3 and HDL Coder 3.11
-- 
-- -------------------------------------------------------------


LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

PACKAGE hdl_modulator_pac IS
  TYPE vector_of_signed16 IS ARRAY (NATURAL RANGE <>) OF signed(15 DOWNTO 0);
  TYPE vector_of_unsigned9 IS ARRAY (NATURAL RANGE <>) OF unsigned(8 DOWNTO 0);
END hdl_modulator_pac;

